trigger:
- master
- pipelines-image

schedules:
- cron: 0 21 * * 0
  always: true
  branches:
    include:
    - master

pool:
  vmImage: ubuntu-latest

variables:
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
    tag: latest
  ${{ if eq(variables['Build.SourceBranchName'], 'pipelines-image') }}:
    tag: latest-dev

steps:
- bash: docker login $(ACR_SERVER_NAME) -u $(ACR_USERNAME) -p $(ACR_PASSWORD)
  displayName: Login to ACR

- bash: docker build --push -t $(ACR_SERVER_NAME)/matatika/example-github-analytics .
  displayName: Build and push image to ACR

- task: ECRPushImage@1
  displayName: Push image to ECR
  inputs:
    awsCredentials: Matatika AWS (Staging)
    regionName: eu-west-2
    imageSource: imagename
    sourceImageName: $(ACR_SERVER_NAME)/matatika/example-github-analytics
    sourceImageTag: ${{ variables.tag }}
    repositoryName: example-github-analytics
    pushTag: ${{ variables.tag }}
    autoCreateRepository: true
