trigger:
- master
- pipelines-image

schedules:
- cron: 0 21 * * 0
  always: true
  branches:
    include:
    - master

pool:
  vmImage: ubuntu-latest

variables:
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
    tag: latest
  ${{ if eq(variables['Build.SourceBranchName'], 'pipelines-image') }}:
    tag: latest-dev

steps:
- bash: docker login $(ACR_SERVER_NAME) -u $(ACR_USERNAME) -p $(ACR_PASSWORD)
  displayName: Login to ACR

- bash: docker build -t $(ACR_SERVER_NAME)/matatika/example-github-analytics:${{ variables.tag }} .
  displayName: Build image

- bash: docker push $(ACR_SERVER_NAME)/matatika/example-github-analytics:${{ variables.tag }}
  displayName: Push image to ACR
