version: 1
default_environment: dev
project_id: 9f43b189-d108-4019-9f68-41979d6455ae
environments:
- name: dev
- name: staging
- name: prod
plugins:
  extractors:
  - name: tap-github
    variant: matatika
    pip_url: git+https://github.com/MeltanoLabs/tap-github.git
    select:
    - '*!.*'
    - issues.*
    - repositories.*
    - pull_requests.*
    - commits.*
  loaders:
  - name: target-postgres
    variant: transferwise
    pip_url: git+https://github.com/Matatika/pipelinewise-target-postgres@v0.1.0
    annotations:
      matatika:
        properties_from_datastore: Warehouse
  transforms:
  - name: dbt-tap-github
    variant: matatika
    pip_url: https://github.com/Matatika/dbt-tap-github@v0.2.0
  transformers:
  - name: dbt
    variant: dbt-labs
    pip_url: "dbt-core~=1.3.0 dbt-postgres~=1.3.0 dbt-snowflake~=1.3.0\n"
  files:
  - name: analyze-github
    variant: matatika
    pip_url: git+https://github.com/Matatika/analyze-github
  utilities:
  - name: matatika
    variant: matatika
    pip_url: git+https://github.com/Matatika/matatika-ext.git@v0.9.0
jobs:
- name: github-job
  tasks:
  - tap-github
  - target-postgres
  - dbt:deps
  - dbt:snapshot
  - dbt:run
schedules:
- name: GitHub
  interval: 0 0 * * * *
  job: github-job
