# This file is managed by the 'files-matatika-lab' file bundle and updated automatically when `meltano upgrade` is run.
# To prevent any manual changes from being overwritten, remove the file bundle from `meltano.yml` or disable automatic updates:
#     meltano config --plugin-type=files files-matatika-lab set _update orchestrate/matatika/elastic-search/config/instances.yml false

# elastic search instances
instances:
  - name: 'search'
    dns: [ 'search', 'localhost' ]
  - name: 'search02'
    dns: [ 'search02', 'localhost' ]
  - name: 'logstash'
    dns: [ 'logstash', 'logstash.local' ]
